/*
 * Copyright (c) 2018
 * kamical india pvt Ltd.
 * village+PO saharda,Ps Pingla
 * Dist Paschim Medinipur
 * State WestBengal
 * Pin 721131
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the the copyright holder nor the
 *    names of its contributors may be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
package com.kamical.balance.model;

import java.util.LinkedHashMap;

/**
 * @purpose Primary method that balances an input chemical equation.
 *          <p>
 *          Examples:
 *
 *          {@link https://gist.github.com/felixdivo/11159677 for
 *          electronegativity data collect}
 * @param equation
 * @return String or null
 * @author kartik.cse43 &lt;kartik.cse43@gmail.com&gt;
 */
public class PeriodicTable {
	static LinkedHashMap<String, Element> periodicTableAtomNameMap;
	static LinkedHashMap<Integer, Element> periodicTableAtomNumberMap;
	static String[] valancy = null;

	/**
	 * @purpose This is all initial value of All element of Chemical.
	 *          <p>
	 *          Examples:
	 * @param private static PeriodicTable table
	 * @author kartik.cse43 &lt;kartik.cse43@gmail.com&gt;
	 */
	public static void setInitialValues() {
		periodicTableAtomNameMap = new LinkedHashMap<String, Element>();
		periodicTableAtomNumberMap = new LinkedHashMap<Integer, Element>();
		Element mv = new Element();
		mv.setPeriodicId(1);
		mv.setMoleSymbol("H");
		mv.setMoleName("Hydrogen");
		mv.setWeight(new Double(1.0079));
		mv.setDefaultAtomValancy("+1");
		mv.setElectroNegativity(2.1f);
		mv.setType("Non-Metals");
		valancy = new String[2];
		valancy[0] = "+1";
		valancy[1] = "-1";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("H", mv);
		periodicTableAtomNumberMap.put(1,mv);
		mv = new Element();
		mv.setPeriodicId(2);
		mv.setMoleSymbol("He");
		mv.setMoleName("Helium");
		mv.setWeight(new Double(4.0026));
		mv.setDefaultAtomValancy("0");
		mv.setElectroNegativity(0f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "0";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("He", mv);
		periodicTableAtomNumberMap.put(2,mv);
		mv = new Element();
		mv.setPeriodicId(3);
		mv.setMoleSymbol("Li");
		mv.setMoleName("Lithium");
		mv.setWeight(new Double(6.941));
		mv.setDefaultAtomValancy("+1");
		mv.setElectroNegativity(0.98f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "+1";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Li", mv);
		periodicTableAtomNumberMap.put(3,mv);
		mv = new Element();
		mv.setPeriodicId(4);
		mv.setMoleSymbol("Be");
		mv.setMoleName("Beryllium");
		mv.setWeight(new Double(9.0122));
		mv.setDefaultAtomValancy("+2");
		mv.setElectroNegativity(1.57f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "+2";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Be", mv);
		periodicTableAtomNumberMap.put(4,mv);
		mv = new Element();
		mv.setPeriodicId(5);
		mv.setMoleSymbol("B");
		mv.setMoleName("Boron");
		mv.setWeight(new Double(10.811));
		mv.setElectroNegativity(2.04f);
		mv.setType("Metalloids");
		valancy = null;
		valancy = new String[2];
		valancy[0] = "-3";
		valancy[1] = "+3";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("B", mv);
		periodicTableAtomNumberMap.put(5,mv);
		mv = new Element();
		mv.setPeriodicId(6);
		mv.setMoleSymbol("C");
		mv.setMoleName("Carbon");
		mv.setWeight(new Double(12.0107));
		mv.setDefaultAtomValancy("+4");
		mv.setElectroNegativity(2.55f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[2];
		valancy[0] = "+2";
		valancy[1] = "+4";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("C", mv);
		periodicTableAtomNumberMap.put(6,mv);
		mv = new Element();
		mv.setPeriodicId(7);
		mv.setMoleSymbol("N");
		mv.setMoleName("Nitrogen");
		mv.setWeight(new Double(14.0067));
		mv.setDefaultAtomValancy("-3");
		mv.setElectroNegativity(3.04f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[8];
		valancy[0] = "-3";
		valancy[1] = "-2";
		valancy[2] = "-1";
		valancy[3] = "+1";
		valancy[4] = "+2";
		valancy[5] = "+3";
		valancy[6] = "+4";
		valancy[7] = "+5";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("N", mv);
		periodicTableAtomNumberMap.put(7,mv);
		mv = new Element();
		mv.setPeriodicId(8);
		mv.setMoleSymbol("O");
		mv.setMoleName("Oxygen");
		mv.setWeight(new Double(15.9994));
		mv.setDefaultAtomValancy("-2");
		mv.setElectroNegativity(3.44f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "-2";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("O", mv);
		periodicTableAtomNumberMap.put(8,mv);
		mv = new Element();
		mv.setPeriodicId(9);
		mv.setMoleSymbol("F");
		mv.setMoleName("Fluorine");
		mv.setWeight(new Double(18.9984));
		mv.setDefaultAtomValancy("-1");
		mv.setElectroNegativity(3.98f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[2];
		valancy[0] = "-1";
		valancy[1] = "+1";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("F", mv);
		periodicTableAtomNumberMap.put(9,mv);
		mv = new Element();
		mv.setPeriodicId(10);
		mv.setMoleSymbol("Ne");
		mv.setMoleName("Neon");
		mv.setWeight(new Double(20.1797));
		mv.setElectroNegativity(0f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "0";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Ne", mv);
		periodicTableAtomNumberMap.put(10,mv);
		mv = new Element();
		mv.setPeriodicId(11);
		mv.setMoleSymbol("Na");
		mv.setMoleName("Sodium");
		mv.setWeight(new Double(22.9897));
		mv.setDefaultAtomValancy("+1");
		mv.setElectroNegativity(0.93f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "+1";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Na", mv);
		periodicTableAtomNumberMap.put(11,mv);
		mv = new Element();
		mv.setPeriodicId(12);
		mv.setMoleSymbol("Mg");
		mv.setMoleName("Magnesium");
		mv.setWeight(new Double(24.305));
		mv.setDefaultAtomValancy("+2");
		mv.setElectroNegativity(1.31f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "+2";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Mg", mv);
		periodicTableAtomNumberMap.put(12,mv);
		mv = new Element();
		mv.setPeriodicId(13);
		mv.setMoleSymbol("Al");
		mv.setMoleName("Aluminium (aluminum)");
		mv.setWeight(new Double(26.9815));
		mv.setDefaultAtomValancy("+3");
		mv.setElectroNegativity(1.61f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "+3";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Al", mv);
		periodicTableAtomNumberMap.put(13,mv);
		mv = new Element();
		mv.setPeriodicId(14);
		mv.setMoleSymbol("Si");
		mv.setMoleName("Silicon");
		mv.setWeight(new Double(28.0855));
		mv.setDefaultAtomValancy("+4");
		mv.setElectroNegativity(1.9f);
		mv.setType("Metalloids");
		valancy = null;
		valancy = new String[3];
		valancy[0] = "-4";
		valancy[1] = "+2";
		valancy[2] = "+4";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Si", mv);
		periodicTableAtomNumberMap.put(14,mv);
		mv = new Element();
		mv.setPeriodicId(15);
		mv.setMoleSymbol("P");
		mv.setMoleName("Phosphorus");
		mv.setWeight(new Double(30.9738));
		mv.setDefaultAtomValancy("+3");
		mv.setElectroNegativity(2.19f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[4];
		valancy[0] = "-3";
		valancy[1] = "+1";
		valancy[2] = "+3";
		valancy[3] = "+5";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("P", mv);
		periodicTableAtomNumberMap.put(15,mv);
		mv = new Element();
		mv.setPeriodicId(16);
		mv.setMoleSymbol("S");
		mv.setMoleName("Sulfur (Sulphur)");
		mv.setWeight(new Double(32.065));
		mv.setDefaultAtomValancy("+6");
		mv.setElectroNegativity(2.58f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[4];
		valancy[0] = "-2";
		valancy[1] = "+2";
		valancy[2] = "+4";
		valancy[3] = "+6";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("S", mv);
		mv = new Element();
		mv.setPeriodicId(17);
		mv.setMoleSymbol("Cl");
		mv.setMoleName("Chlorine");
		mv.setWeight(new Double(35.453));
		mv.setDefaultAtomValancy("-1");
		mv.setElectroNegativity(3.16f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[7];
		valancy[0] = "-1";
		valancy[1] = "+1";
		valancy[2] = "+2";
		valancy[3] = "+3";
		valancy[4] = "+4";
		valancy[5] = "+5";
		valancy[6] = "+7";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Cl", mv);
		periodicTableAtomNumberMap.put(17,mv);
		mv = new Element();
		mv.setPeriodicId(18);
		mv.setMoleSymbol("Ar");
		mv.setMoleName("Argon");
		mv.setWeight(new Double(39.948));
		mv.setDefaultAtomValancy("0");
		mv.setElectroNegativity(0f);
		mv.setType("Non-Metals");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "0";
		mv.setValency(valancy);
		periodicTableAtomNumberMap.put(18,mv);
		periodicTableAtomNameMap.put("Ar", mv);
		mv = new Element();
		mv.setPeriodicId(19);
		mv.setMoleSymbol("K");
		mv.setMoleName("Potassium");
		mv.setWeight(new Double(39.0983));
		mv.setDefaultAtomValancy("+1");
		mv.setElectroNegativity(0.82f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "+1";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("K", mv);
		periodicTableAtomNumberMap.put(19,mv);
		mv = new Element();
		mv.setPeriodicId(20);
		mv.setMoleSymbol("Ca");
		mv.setMoleName("Calcium");
		mv.setWeight(new Double(40.078));
		mv.setDefaultAtomValancy("+2");
		mv.setElectroNegativity(1f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "+2";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Ca", mv);
		periodicTableAtomNumberMap.put(20,mv);
		mv = new Element();
		mv.setPeriodicId(21);
		mv.setMoleSymbol("Sc");
		mv.setMoleName("Scandium");
		mv.setWeight(new Double(44.9559));
		mv.setDefaultAtomValancy("+3");
		mv.setElectroNegativity(1.36f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[3];
		valancy[0] = "+2";
		valancy[1] = "+3";
		valancy[2] = "+4";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Sc", mv);
		periodicTableAtomNumberMap.put(21,mv);
		mv = new Element();
		mv.setPeriodicId(22);
		mv.setMoleSymbol("Ti");
		mv.setMoleName("Titanium");
		mv.setWeight(new Double(47.867));
		mv.setDefaultAtomValancy("+4");
		mv.setElectroNegativity(1.54f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[3];
		valancy[0] = "+2";
		valancy[1] = "+3";
		valancy[2] = "+4";
		mv.setValency(valancy);
		periodicTableAtomNumberMap.put(22,mv);
		periodicTableAtomNameMap.put("Ti", mv);
		mv = new Element();
		mv.setPeriodicId(23);
		mv.setMoleSymbol("V");
		mv.setMoleName("Vanadium");
		mv.setWeight(new Double(50.9415));
		mv.setDefaultAtomValancy("+5");
		mv.setElectroNegativity(1.63f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[4];
		valancy[0] = "+2";
		valancy[1] = "+3";
		valancy[2] = "+4";
		valancy[3] = "+5";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("V", mv);
		periodicTableAtomNumberMap.put(23,mv);
		mv = new Element();
		mv.setPeriodicId(24);
		mv.setMoleSymbol("Cr");
		mv.setMoleName("Chromium");
		mv.setWeight(new Double(51.9961));
		mv.setDefaultAtomValancy("+3");
		mv.setElectroNegativity(1.66f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[3];
		valancy[0] = "+2";
		valancy[1] = "+3";
		valancy[2] = "+6";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Cr", mv);
		periodicTableAtomNumberMap.put(24,mv);
		mv = new Element();
		mv.setPeriodicId(25);
		mv.setMoleSymbol("Mn");
		mv.setMoleName("Manganese");
		mv.setWeight(new Double(54.938));
		mv.setDefaultAtomValancy("+2");
		mv.setElectroNegativity(1.55f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[5];
		valancy[0] = "+2";
		valancy[1] = "+3";
		valancy[2] = "+4";
		valancy[3] = "+6";
		valancy[4] = "+7";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Mn", mv);
		periodicTableAtomNumberMap.put(25,mv);
		mv = new Element();
		mv.setPeriodicId(26);
		mv.setMoleSymbol("Fe");
		mv.setMoleName("Iron");
		mv.setWeight(new Double(55.845));
		mv.setDefaultAtomValancy("+3");
		mv.setElectroNegativity(1.83f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[4];
		valancy[0] = "+2";
		valancy[1] = "+3";
		valancy[2] = "+4";
		valancy[3] = "+6";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Fe", mv);
		periodicTableAtomNumberMap.put(26,mv);
		mv = new Element();
		mv.setPeriodicId(27);
		mv.setMoleSymbol("Co");
		mv.setMoleName("Cobalt");
		mv.setWeight(new Double(58.9332));
		mv.setDefaultAtomValancy("+2");
		mv.setElectroNegativity(1.88f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[3];
		valancy[0] = "+2";
		valancy[1] = "+3";
		valancy[2] = "+4";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Co", mv);
		periodicTableAtomNumberMap.put(27,mv);
		mv = new Element();
		mv.setPeriodicId(28);
		mv.setMoleSymbol("Ni");
		mv.setMoleName("Nickel");
		mv.setWeight(new Double(58.6934));
		mv.setDefaultAtomValancy("+2");
		mv.setElectroNegativity(1.91f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[4];
		valancy[0] = "+1";
		valancy[1] = "+2";
		valancy[2] = "+3";
		valancy[3] = "+4";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Ni", mv);
		periodicTableAtomNumberMap.put(28,mv);
		mv = new Element();
		mv.setPeriodicId(29);
		mv.setMoleSymbol("Cu");
		mv.setMoleName("Copper");
		mv.setWeight(new Double(63.546));
		mv.setDefaultAtomValancy("+2");
		mv.setElectroNegativity(1.9f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[3];
		valancy[0] = "+1";
		valancy[1] = "+2";
		valancy[2] = "+3";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Cu", mv);
		periodicTableAtomNumberMap.put(29,mv);
		mv = new Element();
		mv.setPeriodicId(30);
		mv.setMoleSymbol("Zn");
		mv.setMoleName("Zinc");
		mv.setWeight(new Double(65.39));
		mv.setDefaultAtomValancy("+2");
		mv.setElectroNegativity(1.65f);
		mv.setType("Metal");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "+2";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("Zn", mv);
		periodicTableAtomNumberMap.put(30,mv);
		mv = new Element();
		mv.setPeriodicId(31);
		mv.setMoleSymbol("Ga");
		mv.setMoleName("Gallium");
		mv.setWeight(new Double(69.723));
		mv.setElectroNegativity(1.81f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ga", mv);
		periodicTableAtomNumberMap.put(31,mv);
		mv = new Element();
		mv.setPeriodicId(32);
		mv.setMoleSymbol("Ge");
		mv.setMoleName("Germanium");
		mv.setWeight(new Double(72.64));
		mv.setElectroNegativity(2.01f);
		mv.setType("Metalloids");
		periodicTableAtomNameMap.put("Ge", mv);
		periodicTableAtomNumberMap.put(32,mv);
		mv = new Element();
		mv.setPeriodicId(33);
		mv.setMoleSymbol("As");
		mv.setMoleName("Arsenic");
		mv.setWeight(new Double(74.9216));
		mv.setElectroNegativity(2.18f);
		mv.setType("Metalloids");
		periodicTableAtomNameMap.put("As", mv);
		periodicTableAtomNumberMap.put(33,mv);
		mv = new Element();
		mv.setPeriodicId(34);
		mv.setMoleSymbol("Se");
		mv.setMoleName("Selenium");
		mv.setWeight(new Double(78.96));
		mv.setElectroNegativity(2.55f);
		mv.setType("Non-Metals");
		periodicTableAtomNameMap.put("Se", mv);
		periodicTableAtomNumberMap.put(34,mv);
		mv = new Element();
		mv.setPeriodicId(35);
		mv.setMoleSymbol("Br");
		mv.setMoleName("Bromine");
		mv.setWeight(new Double(79.904));
		mv.setElectroNegativity(2.96f);
		mv.setType("Non-Metals");
		periodicTableAtomNameMap.put("Br", mv);
		periodicTableAtomNumberMap.put(35,mv);
		mv = new Element();
		mv.setPeriodicId(36);
		mv.setMoleSymbol("Kr");
		mv.setMoleName("Krypton");
		mv.setWeight(new Double(83.8));
		mv.setElectroNegativity(0f);
		mv.setType("Non-Metals");
		periodicTableAtomNameMap.put("Kr", mv);
		periodicTableAtomNumberMap.put(36,mv);
		mv = new Element();
		mv.setPeriodicId(37);
		mv.setMoleSymbol("Rb");
		mv.setMoleName("Rubidium");
		mv.setWeight(new Double(85.4678));
		mv.setElectroNegativity(0.82f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Rb", mv);
		periodicTableAtomNumberMap.put(37,mv);
		mv = new Element();
		mv.setPeriodicId(38);
		mv.setMoleSymbol("Sr");
		mv.setMoleName("Strontium");
		mv.setWeight(new Double(87.62));
		mv.setElectroNegativity(0.95f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Sr", mv);
		periodicTableAtomNumberMap.put(38,mv);
		mv = new Element();
		mv.setPeriodicId(39);
		mv.setMoleSymbol("Y");
		mv.setMoleName("Yttrium");
		mv.setWeight(new Double(88.9059));
		mv.setElectroNegativity(1.22f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Y", mv);
		periodicTableAtomNumberMap.put(39,mv);
		mv = new Element();
		mv.setPeriodicId(40);
		mv.setMoleSymbol("Zr");
		mv.setMoleName("Zirconium");
		mv.setWeight(new Double(91.224));
		mv.setElectroNegativity(1.33f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Zr", mv);
		periodicTableAtomNumberMap.put(40,mv);
		mv = new Element();
		mv.setPeriodicId(41);
		mv.setMoleSymbol("Nb");
		mv.setMoleName("Niobium");
		mv.setWeight(new Double(92.9064));
		mv.setElectroNegativity(1.6f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Nb", mv);
		periodicTableAtomNumberMap.put(41,mv);
		mv = new Element();
		mv.setPeriodicId(42);
		mv.setMoleSymbol("Mo");
		mv.setMoleName("Molybdenum");
		mv.setWeight(new Double(95.94));
		mv.setElectroNegativity(2.16f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Mo", mv);
		periodicTableAtomNumberMap.put(42,mv);
		mv = new Element();
		mv.setPeriodicId(43);
		mv.setMoleSymbol("Tc");
		mv.setMoleName("Technetium");
		mv.setWeight(new Double(98));
		mv.setElectroNegativity(1.9f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Tc", mv);
		periodicTableAtomNumberMap.put(43,mv);
		mv = new Element();
		mv.setPeriodicId(44);
		mv.setMoleSymbol("Ru");
		mv.setMoleName("Ruthenium");
		mv.setWeight(new Double(101.07));
		mv.setElectroNegativity(2.2f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ru", mv);
		periodicTableAtomNumberMap.put(44,mv);
		mv = new Element();
		mv.setPeriodicId(45);
		mv.setMoleSymbol("Rh");
		mv.setMoleName("Rhodium");
		mv.setWeight(new Double(102.9055));
		mv.setElectroNegativity(2.28f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Rh", mv);
		periodicTableAtomNumberMap.put(45,mv);
		mv = new Element();
		mv.setPeriodicId(46);
		mv.setMoleSymbol("Pd");
		mv.setMoleName("Palladium");
		mv.setWeight(new Double(106.42));
		mv.setElectroNegativity(2.2f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Pd", mv);
		periodicTableAtomNumberMap.put(46,mv);
		mv = new Element();
		mv.setPeriodicId(47);
		mv.setMoleSymbol("Ag");
		mv.setMoleName("Silver");
		mv.setWeight(new Double(107.8682));
		mv.setElectroNegativity(1.93f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ag", mv);
		periodicTableAtomNumberMap.put(47,mv);
		mv = new Element();
		mv.setPeriodicId(48);
		mv.setMoleSymbol("Cd");
		mv.setMoleName("Cadmium");
		mv.setWeight(new Double(112.411));
		mv.setElectroNegativity(1.69f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Cd", mv);
		periodicTableAtomNumberMap.put(48,mv);
		mv = new Element();
		mv.setPeriodicId(49);
		mv.setMoleSymbol("In");
		mv.setMoleName("Indium");
		mv.setWeight(new Double(114.818));
		mv.setElectroNegativity(1.78f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("In", mv);
		periodicTableAtomNumberMap.put(49,mv);
		mv = new Element();
		mv.setPeriodicId(50);
		mv.setMoleSymbol("Sn");
		mv.setMoleName("Tin");
		mv.setWeight(new Double(118.71));
		mv.setElectroNegativity(1.96f);
		periodicTableAtomNameMap.put("Sn", mv);
		periodicTableAtomNumberMap.put(50,mv);
		mv = new Element();
		mv.setPeriodicId(51);
		mv.setMoleSymbol("Sb");
		mv.setMoleName("Antimony");
		mv.setWeight(new Double(121.76));
		mv.setElectroNegativity(2.05f);
		mv.setType("Metalloids");
		periodicTableAtomNameMap.put("Sb", mv);
		periodicTableAtomNumberMap.put(51,mv);
		mv = new Element();
		mv.setPeriodicId(52);
		mv.setMoleSymbol("Te");
		mv.setMoleName("Tellurium");
		mv.setWeight(new Double(127.6));
		mv.setElectroNegativity(2.1f);
		mv.setType("Metalloids");
		periodicTableAtomNameMap.put("Te", mv);
		periodicTableAtomNumberMap.put(52,mv);
		mv = new Element();
		mv.setPeriodicId(53);
		mv.setMoleSymbol("I");
		mv.setMoleName("Iodine");
		mv.setWeight(new Double(126.9045));
		mv.setElectroNegativity(2.66f);
		mv.setType("Non-Metals");
		periodicTableAtomNameMap.put("I", mv);
		periodicTableAtomNumberMap.put(53,mv);
		mv = new Element();
		mv.setPeriodicId(54);
		mv.setMoleSymbol("Xe");
		mv.setMoleName("Xenon");
		mv.setWeight(new Double(131.293));
		mv.setElectroNegativity(2.6f);
		mv.setType("Non-Metals");
		periodicTableAtomNameMap.put("Xe", mv);
		periodicTableAtomNumberMap.put(54,mv);
		mv = new Element();
		mv.setPeriodicId(55);
		mv.setMoleSymbol("Cs");
		mv.setMoleName("Caesium (Cesium)");
		mv.setWeight(new Double(132.9055));
		mv.setElectroNegativity(0.79f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Cs", mv);
		periodicTableAtomNumberMap.put(55,mv);
		mv = new Element();
		mv.setPeriodicId(56);
		mv.setMoleSymbol("Ba");
		mv.setMoleName("Barium");
		mv.setWeight(new Double(137.327));
		mv.setElectroNegativity(0.89f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ba", mv);
		periodicTableAtomNumberMap.put(56,mv);
		mv = new Element();
		mv.setPeriodicId(57);
		mv.setMoleSymbol("La");
		mv.setMoleName("Lanthanum");
		mv.setWeight(new Double(138.9055));
		mv.setElectroNegativity(1.1f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("La", mv);
		periodicTableAtomNumberMap.put(57,mv);
		mv = new Element();
		mv.setPeriodicId(58);
		mv.setMoleSymbol("Ce");
		mv.setMoleName("Cerium");
		mv.setWeight(new Double(140.116));
		mv.setElectroNegativity(1.12f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ce", mv);
		periodicTableAtomNumberMap.put(58,mv);
		mv = new Element();
		mv.setPeriodicId(59);
		mv.setMoleSymbol("Pr");
		mv.setMoleName("Praseodymium");
		mv.setWeight(new Double(140.9077));
		mv.setElectroNegativity(1.13f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Pr", mv);
		periodicTableAtomNumberMap.put(59,mv);
		mv = new Element();
		mv.setPeriodicId(60);
		mv.setMoleSymbol("Nd");
		mv.setMoleName("Neodymium");
		mv.setWeight(new Double(144.24));
		mv.setElectroNegativity(1.14f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Nd", mv);
		periodicTableAtomNumberMap.put(60,mv);
		mv = new Element();
		mv.setPeriodicId(61);
		mv.setMoleSymbol("Pm");
		mv.setMoleName("Promethium");
		mv.setWeight(new Double(145));
		mv.setElectroNegativity(1.13f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Pm", mv);
		periodicTableAtomNumberMap.put(61,mv);
		mv = new Element();
		mv.setPeriodicId(62);
		mv.setMoleSymbol("Sm");
		mv.setMoleName("Samarium");
		mv.setWeight(new Double(150.36));
		mv.setElectroNegativity(1.17f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Sm", mv);
		periodicTableAtomNumberMap.put(62,mv);
		mv = new Element();
		mv.setPeriodicId(63);
		mv.setMoleSymbol("Eu");
		mv.setMoleName("Europium");
		mv.setWeight(new Double(151.964));
		mv.setElectroNegativity(1.2f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Eu", mv);
		periodicTableAtomNumberMap.put(63,mv);
		mv = new Element();
		mv.setPeriodicId(64);
		mv.setMoleSymbol("Gd");
		mv.setMoleName("Gadolinium");
		mv.setWeight(new Double(157.25));
		mv.setElectroNegativity(1.2f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Gd", mv);
		periodicTableAtomNumberMap.put(64,mv);
		mv = new Element();
		mv.setPeriodicId(65);
		mv.setMoleSymbol("Tb");
		mv.setMoleName("Terbium");
		mv.setWeight(new Double(158.9253));
		mv.setElectroNegativity(1.1f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Tb", mv);
		periodicTableAtomNumberMap.put(65,mv);
		mv = new Element();
		mv.setPeriodicId(66);
		mv.setMoleSymbol("Dy");
		mv.setMoleName("Dysprosium");
		mv.setWeight(new Double(162.5));
		mv.setElectroNegativity(1.22f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Dy", mv);
		periodicTableAtomNumberMap.put(66,mv);
		mv = new Element();
		mv.setPeriodicId(67);
		mv.setMoleSymbol("Ho");
		mv.setMoleName("Holmium");
		mv.setWeight(new Double(164.9303));
		mv.setElectroNegativity(1.23f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ho", mv);
		periodicTableAtomNumberMap.put(67,mv);
		mv = new Element();
		mv.setPeriodicId(68);
		mv.setMoleSymbol("Er");
		mv.setMoleName("Erbium");
		mv.setWeight(new Double(167.259));
		mv.setElectroNegativity(1.24f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Er", mv);
		periodicTableAtomNumberMap.put(68,mv);
		mv = new Element();
		mv.setPeriodicId(69);
		mv.setMoleSymbol("Tm");
		mv.setMoleName("Thulium");
		mv.setWeight(new Double(168.9342));
		mv.setElectroNegativity(1.25f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Tm", mv);
		periodicTableAtomNumberMap.put(69,mv);
		mv = new Element();
		mv.setPeriodicId(70);
		mv.setMoleSymbol("Yb");
		mv.setMoleName("Ytterbium");
		mv.setWeight(new Double(173.04));
		mv.setElectroNegativity(1.1f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Yb", mv);
		periodicTableAtomNumberMap.put(70,mv);
		mv = new Element();
		mv.setPeriodicId(71);
		mv.setMoleSymbol("Lu");
		mv.setMoleName("Lutetium");
		mv.setWeight(new Double(174.967));
		mv.setElectroNegativity(1.27f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Lu", mv);
		periodicTableAtomNumberMap.put(71,mv);
		mv = new Element();
		mv.setPeriodicId(72);
		mv.setMoleSymbol("Hf");
		mv.setMoleName("Hafnium");
		mv.setWeight(new Double(178.49));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Hf", mv);
		periodicTableAtomNumberMap.put(72,mv);
		mv = new Element();
		mv.setPeriodicId(73);
		mv.setMoleSymbol("Ta");
		mv.setMoleName("Tantalum");
		mv.setWeight(new Double(180.9479));
		mv.setElectroNegativity(1.5f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ta", mv);
		periodicTableAtomNumberMap.put(73,mv);
		mv = new Element();
		mv.setPeriodicId(74);
		mv.setMoleSymbol("W");
		mv.setMoleName("Tungsten");
		mv.setWeight(new Double(183.84));
		mv.setElectroNegativity(2.36f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("W", mv);
		periodicTableAtomNumberMap.put(74,mv);
		mv = new Element();
		mv.setPeriodicId(75);
		mv.setMoleSymbol("Re");
		mv.setMoleName("Rhenium");
		mv.setWeight(new Double(186.207));
		mv.setElectroNegativity(1.9f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Re", mv);
		periodicTableAtomNumberMap.put(75,mv);
		mv = new Element();
		mv.setPeriodicId(76);
		mv.setMoleSymbol("Os");
		mv.setMoleName("Osmium");
		mv.setWeight(new Double(190.23));
		mv.setElectroNegativity(2.2f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Os", mv);
		periodicTableAtomNumberMap.put(76,mv);
		mv = new Element();
		mv.setPeriodicId(77);
		mv.setMoleSymbol("Ir");
		mv.setMoleName("Iridium");
		mv.setWeight(new Double(192.217));
		mv.setElectroNegativity(2.2f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ir", mv);
		periodicTableAtomNumberMap.put(77,mv);
		mv = new Element();
		mv.setPeriodicId(78);
		mv.setMoleSymbol("Pt");
		mv.setMoleName("Platinum");
		mv.setWeight(new Double(195.078));
		mv.setElectroNegativity(2.28f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Pt", mv);
		periodicTableAtomNumberMap.put(78,mv);
		mv = new Element();
		mv.setPeriodicId(79);
		mv.setMoleSymbol("Au");
		mv.setMoleName("Gold");
		mv.setWeight(new Double(196.9665));
		mv.setElectroNegativity(2.54f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Au", mv);
		periodicTableAtomNumberMap.put(79,mv);
		mv = new Element();
		mv.setPeriodicId(80);
		mv.setMoleSymbol("Hg");
		mv.setMoleName("Mercury");
		mv.setWeight(new Double(200.59));
		mv.setElectroNegativity(2f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Hg", mv);
		periodicTableAtomNumberMap.put(80,mv);
		mv = new Element();
		mv.setPeriodicId(81);
		mv.setMoleSymbol("Tl");
		mv.setMoleName("Thallium");
		mv.setWeight(new Double(204.3833));
		mv.setElectroNegativity(2.04f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Tl", mv);
		periodicTableAtomNumberMap.put(81,mv);
		mv = new Element();
		mv.setPeriodicId(82);
		mv.setMoleSymbol("Pb");
		mv.setMoleName("Lead");
		mv.setWeight(new Double(207.2));
		mv.setElectroNegativity(2.33f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Pb", mv);
		periodicTableAtomNumberMap.put(82,mv);
		mv = new Element();
		mv.setPeriodicId(83);
		mv.setMoleSymbol("Bi");
		mv.setMoleName("Bismuth");
		mv.setWeight(new Double(208.9804));
		mv.setElectroNegativity(2.02f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Bi", mv);
		periodicTableAtomNumberMap.put(83,mv);
		mv = new Element();
		mv.setPeriodicId(84);
		mv.setMoleSymbol("Po");
		mv.setMoleName("Polonium");
		mv.setWeight(new Double(209));
		mv.setElectroNegativity(2f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Po", mv);
		periodicTableAtomNumberMap.put(84,mv);
		mv = new Element();
		mv.setPeriodicId(85);
		mv.setMoleSymbol("At");
		mv.setMoleName("Astatine");
		mv.setWeight(new Double(210));
		mv.setElectroNegativity(2.2f);
		mv.setType("Metalloids");
		periodicTableAtomNameMap.put("At", mv);
		periodicTableAtomNumberMap.put(85,mv);
		mv = new Element();
		mv.setPeriodicId(86);
		mv.setMoleSymbol("Rn");
		mv.setMoleName("Radon");
		mv.setWeight(new Double(222));
		mv.setElectroNegativity(0f);
		mv.setType("Non-Metals");
		periodicTableAtomNameMap.put("Rn", mv);
		periodicTableAtomNumberMap.put(86,mv);
		mv = new Element();
		mv.setPeriodicId(87);
		mv.setMoleSymbol("Fr");
		mv.setMoleName("Francium");
		mv.setWeight(new Double(223));
		mv.setElectroNegativity(0.7f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Fr", mv);
		periodicTableAtomNumberMap.put(87,mv);
		mv = new Element();
		mv.setPeriodicId(88);
		mv.setMoleSymbol("Ra");
		mv.setMoleName("Radium");
		mv.setWeight(new Double(226));
		mv.setElectroNegativity(0.89f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ra", mv);
		periodicTableAtomNumberMap.put(88,mv);
		mv = new Element();
		mv.setPeriodicId(89);
		mv.setMoleSymbol("Ac");
		mv.setMoleName("Actinium");
		mv.setWeight(new Double(227));
		mv.setElectroNegativity(1.1f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ac", mv);
		periodicTableAtomNumberMap.put(89,mv);
		mv = new Element();
		mv.setPeriodicId(90);
		mv.setMoleSymbol("Th");
		mv.setMoleName("Thorium");
		mv.setWeight(new Double(231.0359));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Th", mv);
		periodicTableAtomNumberMap.put(90,mv);
		mv = new Element();
		mv.setPeriodicId(91);
		mv.setMoleSymbol("Pa");
		mv.setMoleName("Protactinium");
		mv.setWeight(new Double(232.0381));
		mv.setElectroNegativity(1.5f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Pa", mv);
		periodicTableAtomNumberMap.put(91,mv);
		mv = new Element();
		mv.setPeriodicId(92);
		mv.setMoleSymbol("U");
		mv.setMoleName("Uranium");
		mv.setWeight(new Double(238.0289));
		mv.setElectroNegativity(1.38f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("U", mv);
		periodicTableAtomNumberMap.put(92,mv);
		mv = new Element();
		mv.setPeriodicId(93);
		mv.setMoleSymbol("Np");
		mv.setMoleName("Neptunium");
		mv.setWeight(new Double(237));
		mv.setElectroNegativity(1.36f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Np", mv);
		periodicTableAtomNumberMap.put(93,mv);
		mv = new Element();
		mv.setPeriodicId(94);
		mv.setMoleSymbol("Pu");
		mv.setMoleName("Plutonium");
		mv.setWeight(new Double(244));
		mv.setElectroNegativity(1.28f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Pu", mv);
		periodicTableAtomNumberMap.put(94,mv);
		mv = new Element();
		mv.setPeriodicId(95);
		mv.setMoleSymbol("Am");
		mv.setMoleName("Americium");
		mv.setWeight(new Double(243));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Am", mv);
		periodicTableAtomNumberMap.put(95,mv);
		mv = new Element();
		mv.setPeriodicId(96);
		mv.setMoleSymbol("Cm");
		mv.setMoleName("Curium");
		mv.setWeight(new Double(247));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Cm", mv);
		periodicTableAtomNumberMap.put(96,mv);
		mv = new Element();
		mv.setPeriodicId(97);
		mv.setMoleSymbol("Bk");
		mv.setMoleName("Berkelium");
		mv.setWeight(new Double(247));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Bk", mv);
		periodicTableAtomNumberMap.put(97,mv);
		mv = new Element();
		mv.setPeriodicId(98);
		mv.setMoleSymbol("Cf");
		mv.setMoleName("Californium");
		mv.setWeight(new Double(251));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Cf", mv);
		periodicTableAtomNumberMap.put(98,mv);
		mv = new Element();
		mv.setPeriodicId(99);
		mv.setMoleSymbol("Es");
		mv.setMoleName("Einsteinium");
		mv.setWeight(new Double(252));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Es", mv);
		periodicTableAtomNumberMap.put(99,mv);
		mv = new Element();
		mv.setPeriodicId(100);
		mv.setMoleSymbol("Fm");
		mv.setMoleName("Fermium");
		mv.setWeight(new Double(257));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Em", mv);
		periodicTableAtomNumberMap.put(100,mv);
		mv = new Element();
		mv.setPeriodicId(101);
		mv.setMoleSymbol("Md");
		mv.setMoleName("Mendelevium");
		mv.setWeight(new Double(258));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Md", mv);
		periodicTableAtomNumberMap.put(101,mv);
		mv = new Element();
		mv.setPeriodicId(102);
		mv.setMoleSymbol("No");
		mv.setMoleName("Nobelium");
		mv.setWeight(new Double(259));
		mv.setElectroNegativity(1.3f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("No", mv);
		periodicTableAtomNumberMap.put(102,mv);
		mv = new Element();
		mv.setPeriodicId(103);
		mv.setMoleSymbol("Rf");
		mv.setMoleName("Lawrencium");
		mv.setWeight(new Double(261));
		mv.setElectroNegativity(0f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Rf", mv);
		periodicTableAtomNumberMap.put(103,mv);
		mv = new Element();
		mv.setPeriodicId(104);
		mv.setMoleSymbol("Lr");
		mv.setMoleName("Rutherfordium");
		mv.setWeight(new Double(262));
		mv.setElectroNegativity(0f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Lr", mv);
		periodicTableAtomNumberMap.put(104,mv);
		mv = new Element();
		mv.setPeriodicId(105);
		mv.setMoleSymbol("Db");
		mv.setMoleName("Dubnium");
		mv.setWeight(new Double(262));
		mv.setElectroNegativity(0f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Db", mv);
		periodicTableAtomNumberMap.put(105,mv);
		mv = new Element();
		mv.setPeriodicId(106);
		mv.setMoleSymbol("Sg");
		mv.setMoleName("Seaborgium");
		mv.setWeight(new Double(266));
		mv.setElectroNegativity(0f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Sg", mv);
		periodicTableAtomNumberMap.put(106,mv);
		mv = new Element();
		mv.setPeriodicId(107);
		mv.setMoleSymbol("Bh");
		mv.setMoleName("Bohrium");
		mv.setWeight(new Double(264));
		mv.setElectroNegativity(0f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Bh", mv);
		periodicTableAtomNumberMap.put(107,mv);
		mv = new Element();
		mv.setPeriodicId(108);
		mv.setMoleSymbol("Hs");
		mv.setMoleName("Hassium");
		mv.setWeight(new Double(277));
		mv.setElectroNegativity(0f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Hs", mv);
		periodicTableAtomNumberMap.put(108,mv);
		mv = new Element();
		mv.setPeriodicId(109);
		mv.setMoleSymbol("Mt");
		mv.setMoleName("Meitnerium");
		mv.setWeight(new Double(268));
		mv.setElectroNegativity(0f);
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Mt", mv);
		periodicTableAtomNumberMap.put(109,mv);
		mv = new Element();
		mv.setPeriodicId(110);
		mv.setMoleSymbol("Ds");
		mv.setMoleName("Darmstadtium");
		mv.setWeight(new Double(280));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Ds", mv);
		periodicTableAtomNumberMap.put(110,mv);
		mv = new Element();
		mv.setPeriodicId(111);
		mv.setMoleSymbol("Rg");
		mv.setMoleName("Roentgenium");
		mv.setWeight(new Double(272));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Rg", mv);
		periodicTableAtomNumberMap.put(111,mv);
		mv = new Element();
		mv.setPeriodicId(112);
		mv.setMoleSymbol("Cp");
		mv.setMoleName("Copernicium");
		mv.setWeight(new Double(277));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Cp", mv);
		periodicTableAtomNumberMap.put(112,mv);
		mv = new Element();
		mv.setPeriodicId(113);
		mv.setMoleSymbol("Uut");
		mv.setMoleName("Ununtrium");
		mv.setWeight(new Double(280));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Uut", mv);
		periodicTableAtomNumberMap.put(113,mv);
		mv = new Element();
		mv.setPeriodicId(114);
		mv.setMoleSymbol("Fl");
		mv.setMoleName("Ununquadium");
		mv.setWeight(new Double(280));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Fl", mv);
		periodicTableAtomNumberMap.put(114,mv);
		mv = new Element();
		mv.setPeriodicId(115);
		mv.setMoleSymbol("Uup");
		mv.setMoleName("Ununpentium");
		mv.setWeight(new Double(280));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Uup", mv);
		periodicTableAtomNumberMap.put(115,mv);
		mv = new Element();
		mv.setPeriodicId(116);
		mv.setMoleSymbol("Lv");
		mv.setMoleName("Ununhexium");
		mv.setWeight(new Double(280));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Lv", mv);
		periodicTableAtomNumberMap.put(116,mv);
		mv = new Element();
		mv.setPeriodicId(117);
		mv.setMoleSymbol("Uus");
		mv.setMoleName("Ununseptium");
		mv.setWeight(new Double(280));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Uus", mv);
		periodicTableAtomNumberMap.put(117,mv);
		mv = new Element();
		mv.setPeriodicId(118);
		mv.setMoleSymbol("Uuo");
		mv.setMoleName("Ununoctium");
		mv.setWeight(new Double(280));
		mv.setType("Metal");
		periodicTableAtomNameMap.put("Uuo", mv);
		periodicTableAtomNumberMap.put(118,mv);
		
		
		
		
		
		
		/*mv = new Element();
		mv.setPeriodicId(130);
		mv.setMoleSymbol("SO4");
		mv.setMoleName("sulphate");
		mv.setWeight(new Double(96.07));
		mv.setDefaultValancy("-2");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "-2";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("SO4", mv);
		mv = new Element();
		mv.setPeriodicId(131);
		mv.setMoleSymbol("OH");
		mv.setMoleName("Hydroxide");
		mv.setWeight(new Double(17.008));
		mv.setDefaultValancy("-1");
		valancy = null;
		valancy = new String[1];
		valancy[0] = "-1";
		mv.setValency(valancy);
		periodicTableAtomNameMap.put("OH", mv);*/
	}

	/**
	 * @return the hm
	 */
	public static LinkedHashMap<String, Element> getPeriodicTableAtomNameMap() {
		setInitialValues();
		return periodicTableAtomNameMap;
	}

	/**
	 * @param periodicTableAtomNameMap
	 *            the hm to set
	 */
	public static void setPeriodicTableAtomNameMap(LinkedHashMap<String, Element> periodicTableAtomNameMap) {
		PeriodicTable.periodicTableAtomNameMap = periodicTableAtomNameMap;
	}

	/**
	 * @return the periodicTableAtomNumberMap
	 */
	public static LinkedHashMap<Integer, Element> getPeriodicTableAtomNumberMap() {
		return periodicTableAtomNumberMap;
	}

	/**
	 * @param periodicTableAtomNumberMap the periodicTableAtomNumberMap to set
	 */
	public static void setPeriodicTableAtomNumberMap(
			LinkedHashMap<Integer, Element> periodicTableAtomNumberMap) {
		PeriodicTable.periodicTableAtomNumberMap = periodicTableAtomNumberMap;
	}

	/*
	 * private static PeriodicTable getInstance() { if (tbl == null) { tbl = new
	 * PeriodicTable(); } return tbl; }
	 */

}
