package com.kartik.chem.test;

import java.util.Hashtable;

public class PeriodicTable {
	static Hashtable<String,Element> hm;
	static String[] valancy = null;
	//private static PeriodicTable tbl;
	/*
	 * This is all initial value of All element of Chemical
	 */
	
	 public void setInitialValues()
     {
      hm=new Hashtable<String,Element>();
      Element mv=new Element();
      mv.setPeriodicId(1); mv.setMoleSymbol("H");mv.setMoleName("Hydrogen"); mv.setWeight(new Double(1.0079));mv.setDefaultValancy("+1");
      valancy =  new String[2];
      valancy[0] = "+1";
      valancy[1] = "-1";
      mv.setValency(valancy); hm.put("H",mv);
      mv=new Element();
      mv.setPeriodicId(2); mv.setMoleSymbol("He");mv.setMoleName("Helium"); mv.setWeight( new Double(4.0026));mv.setDefaultValancy("0");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "0";
      mv.setValency(valancy);hm.put("He",mv);
      mv=new Element();
      mv.setPeriodicId(3); mv.setMoleSymbol("Li");mv.setMoleName("Lithium");  mv.setWeight( new Double(6.941));mv.setDefaultValancy("+1");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "+1";
      mv.setValency(valancy);hm.put("Li",mv);
      mv=new Element();
      mv.setPeriodicId(4); mv.setMoleSymbol("Be");mv.setMoleName("Beryllium");  mv.setWeight( new Double(9.0122)); mv.setDefaultValancy("+2");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "+2";
      mv.setValency(valancy);hm.put("Be",mv);
      mv=new Element();
      mv.setPeriodicId(5); mv.setMoleSymbol("B");mv.setMoleName("Boron");  mv.setWeight(new Double(10.811));
      valancy =null;
      valancy =  new String[2];
      valancy[0] = "-3";
      valancy[1] = "+3";
      mv.setValency(valancy);hm.put("B",mv);
      mv=new Element();
      mv.setPeriodicId(6); mv.setMoleSymbol("C");mv.setMoleName("Carbon");  mv.setWeight(new Double(12.0107));mv.setDefaultValancy("+4");
      valancy =null;
      valancy =  new String[2];
      valancy[0] = "+2";
      valancy[1] = "+4";
      mv.setValency(valancy);hm.put("C",mv);
      mv=new Element();
      mv.setPeriodicId(7); mv.setMoleSymbol("N");mv.setMoleName("Nitrogen"); mv.setWeight(new Double(14.0067));mv.setDefaultValancy("-3");
      valancy =null;
      valancy =  new String[8];
      valancy[0] = "-3";
      valancy[1] = "-2";
      valancy[2] = "-1";
      valancy[3] = "+1";
      valancy[4] = "+2";
      valancy[5] = "+3";
      valancy[6] = "+4";
      valancy[7] = "+5";
      mv.setValency(valancy);hm.put("N",mv); 
      mv=new Element();
      mv.setPeriodicId(8);  mv.setMoleSymbol("O");mv.setMoleName("Oxygen"); mv.setWeight( new Double(15.9994));mv.setDefaultValancy("-2"); 
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "-2";
      mv.setValency(valancy);hm.put("O",mv);
      mv=new Element();
      mv.setPeriodicId(9); mv.setMoleSymbol("F");mv.setMoleName("Fluorine"); mv.setWeight(new Double(18.9984));mv.setDefaultValancy("-1");
      valancy =null;
      valancy =  new String[2];
      valancy[0] = "-1";
      valancy[1] = "+1";
      mv.setValency(valancy);hm.put("F",mv);
      mv=new Element();
      mv.setPeriodicId(10); mv.setMoleSymbol("Ne");mv.setMoleName("Neon"); mv.setWeight(new Double(20.1797));
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "0";
      mv.setValency(valancy);hm.put("Ne",mv);
      mv=new Element();
      mv.setPeriodicId(11); mv.setMoleSymbol("Na");mv.setMoleName("Sodium"); mv.setWeight(new Double(22.9897));mv.setDefaultValancy("+1");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "+1";
      mv.setValency(valancy);hm.put("Na",mv);
      mv=new Element();
      mv.setPeriodicId(12); mv.setMoleSymbol("Mg");mv.setMoleName("Magnesium"); mv.setWeight(new Double(24.305));mv.setDefaultValancy("+2");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "+2";
      mv.setValency(valancy);hm.put("Mg",mv);
      mv=new Element();
      mv.setPeriodicId(13); mv.setMoleSymbol("Al");mv.setMoleName("Aluminium (aluminum)"); mv.setWeight(new Double(26.9815));mv.setDefaultValancy("+3");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "+3";
      mv.setValency(valancy);hm.put("Al",mv);
      mv=new Element();
      mv.setPeriodicId(14); mv.setMoleSymbol("Si");mv.setMoleName("Silicon"); mv.setWeight( new Double(28.0855));mv.setDefaultValancy("+4");
      valancy =null;
      valancy =  new String[3];
      valancy[0] = "-4";
      valancy[1] = "+2";
      valancy[2] = "+4";
      mv.setValency(valancy); hm.put("Si",mv);
      mv=new Element();
      mv.setPeriodicId(15); mv.setMoleSymbol("P");mv.setMoleName("Phosphorus"); mv.setWeight(new Double(30.9738));mv.setDefaultValancy("+3");
      valancy =null;
      valancy =  new String[4];
      valancy[0] = "-3";
      valancy[1] = "+1";
      valancy[2] = "+3";
      valancy[3] = "+5";
      mv.setValency(valancy);hm.put("P",mv);
      mv=new Element();
      mv.setPeriodicId(16); mv.setMoleSymbol("S");mv.setMoleName("Sulfur (Sulphur)"); mv.setWeight(new Double(32.065));mv.setDefaultValancy("+6");
      valancy =null;
      valancy =  new String[4];
      valancy[0] = "-2";
      valancy[1] = "+2";
      valancy[2] = "+4";
      valancy[3] = "+6";
      mv.setValency(valancy);hm.put("S",mv);
      mv=new Element();
      mv.setPeriodicId(17); mv.setMoleSymbol("Cl");mv.setMoleName("Chlorine"); mv.setWeight(new Double(35.453));mv.setDefaultValancy("-1");
      valancy =null;
      valancy =  new String[7];
      valancy[0] = "-1";
      valancy[1] = "+1";
      valancy[2] = "+2";
      valancy[3] = "+3";
      valancy[4] = "+4";
      valancy[5] = "+5";
      valancy[6] = "+7";
      mv.setValency(valancy);hm.put("Cl",mv);
      mv=new Element();
      mv.setPeriodicId(18); mv.setMoleSymbol("Ar");mv.setMoleName("Argon"); mv.setWeight(new Double(39.948));mv.setDefaultValancy("0");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "0";
      mv.setValency(valancy);hm.put("Ar",mv);
      mv=new Element();
      mv.setPeriodicId(19); mv.setMoleSymbol("K");mv.setMoleName("Potassium");  mv.setWeight(new Double(39.0983));mv.setDefaultValancy("+1");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "+1";
      mv.setValency(valancy);hm.put("K",mv);
      mv=new Element();
      mv.setPeriodicId(20); mv.setMoleSymbol("Ca");mv.setMoleName("Calcium"); mv.setWeight(new Double(40.078));mv.setDefaultValancy("+2");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "+2";
      mv.setValency(valancy);hm.put("Ca",mv);
      mv=new Element();
      mv.setPeriodicId(21); mv.setMoleSymbol("Sc");mv.setMoleName("Scandium"); mv.setWeight(new Double(44.9559));mv.setDefaultValancy("+3");
      valancy =null;
      valancy =  new String[3];
      valancy[0] = "+2";
      valancy[1] = "+3";
      valancy[2] = "+4";
      mv.setValency(valancy);hm.put("Sc",mv);
      mv=new Element();
      mv.setPeriodicId(22); mv.setMoleSymbol("Ti");mv.setMoleName("Titanium"); mv.setWeight(new Double(47.867));mv.setDefaultValancy("+4");
      valancy =null;
      valancy =  new String[3];
      valancy[0] = "+2";
      valancy[1] = "+3";
      valancy[2] = "+4";
      mv.setValency(valancy);hm.put("Ti",mv);
      mv=new Element();
      mv.setPeriodicId(23); mv.setMoleSymbol("V");mv.setMoleName("Vanadium"); mv.setWeight( new Double(50.9415));mv.setDefaultValancy("+5");
      valancy =null;
      valancy =  new String[4];
      valancy[0] = "+2";
      valancy[1] = "+3";
      valancy[2] = "+4";
      valancy[3] = "+5";
      mv.setValency(valancy);hm.put("V",mv);
      mv=new Element();
      mv.setPeriodicId(24); mv.setMoleSymbol("Cr");mv.setMoleName("Chromium"); mv.setWeight(new Double(51.9961));mv.setDefaultValancy("+3");
      valancy =null;
      valancy =  new String[3];
      valancy[0] = "+2";
      valancy[1] = "+3";
      valancy[2] = "+6";
      mv.setValency(valancy);hm.put("Cr",mv);
      mv=new Element();
      mv.setPeriodicId(25); mv.setMoleSymbol("Mn");mv.setMoleName("Manganese"); mv.setWeight( new Double(54.938));mv.setDefaultValancy("+2");
      valancy =null;
      valancy =  new String[5];
      valancy[0] = "+2";
      valancy[1] = "+3";
      valancy[2] = "+4";
      valancy[3] = "+6";
      valancy[4] = "+7";
      mv.setValency(valancy);hm.put("Mn",mv);
      mv=new Element();
      mv.setPeriodicId(26); mv.setMoleSymbol("Fe");mv.setMoleName("Iron"); mv.setWeight(new Double(55.845));mv.setDefaultValancy("+3");
      valancy =null;
      valancy =  new String[4];
      valancy[0] = "+2";
      valancy[1] = "+3";
      valancy[2] = "+4";
      valancy[3] = "+6";
      mv.setValency(valancy);hm.put("Fe",mv);
      mv=new Element();
      mv.setPeriodicId(27); mv.setMoleSymbol("Co");mv.setMoleName("Cobalt"); mv.setWeight( new Double(58.9332));mv.setDefaultValancy("+2");
      valancy =null;
      valancy =  new String[3];
      valancy[0] = "+2";
      valancy[1] = "+3";
      valancy[2] = "+4";
      mv.setValency(valancy);hm.put("Co",mv);
      mv=new Element();
      mv.setPeriodicId(28); mv.setMoleSymbol("Ni");mv.setMoleName("Nickel"); mv.setWeight( new Double(58.6934));mv.setDefaultValancy("+2");
      valancy =null;
      valancy =  new String[4];
      valancy[0] = "+1";
      valancy[1] = "+2";
      valancy[2] = "+3";
      valancy[3] = "+4";
      mv.setValency(valancy);hm.put("Ni",mv);
      mv=new Element();
      mv.setPeriodicId(29); mv.setMoleSymbol("Cu");mv.setMoleName("Copper"); mv.setWeight(new Double(63.546));mv.setDefaultValancy("+2");
      valancy =null;
      valancy =  new String[3];
      valancy[0] = "+1";
      valancy[1] = "+2";
      valancy[2] = "+3";
      mv.setValency(valancy);hm.put("Cu",mv);
      mv=new Element();
      mv.setPeriodicId(30); mv.setMoleSymbol("Zn");mv.setMoleName("Zinc"); mv.setWeight(new Double(65.39));mv.setDefaultValancy("+2");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "+2";
      mv.setValency(valancy);hm.put("Zn",mv);
      mv=new Element();
      mv.setPeriodicId(31); mv.setMoleSymbol("Ga");mv.setMoleName("Gallium"); mv.setWeight(new Double(69.723)); hm.put("Ga",mv);
      mv=new Element();
      mv.setPeriodicId(32); mv.setMoleSymbol("Ge");mv.setMoleName("Germanium"); mv.setWeight( new Double(72.64)); hm.put("Ge",mv);
      mv=new Element();
      mv.setPeriodicId(33); mv.setMoleSymbol("As");mv.setMoleName("Arsenic"); mv.setWeight(new Double(74.9216)); hm.put("As",mv);
      mv=new Element();
      mv.setPeriodicId(34); mv.setMoleSymbol("Se");mv.setMoleName("Selenium"); mv.setWeight( new Double(78.96)); hm.put("Se",mv);
      mv=new Element();
      mv.setPeriodicId(35); mv.setMoleSymbol("Br");mv.setMoleName("Bromine"); mv.setWeight( new Double(79.904)); hm.put("Br",mv);
      mv=new Element();
      mv.setPeriodicId(36); mv.setMoleSymbol("Kr");mv.setMoleName("Krypton"); mv.setWeight( new Double(83.8)); hm.put("Kr",mv);
      mv=new Element();
      mv.setPeriodicId(37); mv.setMoleSymbol("Rb");mv.setMoleName("Rubidium"); mv.setWeight( new Double(85.4678)); hm.put("Rb",mv);
      mv=new Element();
      mv.setPeriodicId(38); mv.setMoleSymbol("Sr");mv.setMoleName("Strontium"); mv.setWeight( new Double(87.62)); hm.put("Sr",mv);
      mv=new Element();
      mv.setPeriodicId(39); mv.setMoleSymbol("Y");mv.setMoleName("Yttrium"); mv.setWeight(new Double(88.9059));  hm.put("Y",mv);
      mv=new Element();
      mv.setPeriodicId(40); mv.setMoleSymbol("Zr");mv.setMoleName("Zirconium"); mv.setWeight( new Double(91.224)); hm.put("Zr",mv);
      mv=new Element();
      mv.setPeriodicId(41); mv.setMoleSymbol("Nb");mv.setMoleName("Niobium"); mv.setWeight( new Double(92.9064)); hm.put("Nb",mv);
      mv=new Element();
      mv.setPeriodicId(42); mv.setMoleSymbol("Mo");mv.setMoleName("Molybdenum"); mv.setWeight(new Double(95.94)); hm.put("Mo",mv);
      mv=new Element();
      mv.setPeriodicId(43); mv.setMoleSymbol("Tc");mv.setMoleName("Technetium"); mv.setWeight(new Double(98)); hm.put("Tc",mv);
      mv=new Element();
      mv.setPeriodicId(44); mv.setMoleSymbol("Ru");mv.setMoleName("Ruthenium"); mv.setWeight(new Double(101.07)); hm.put("Ru",mv);
      mv=new Element();
      mv.setPeriodicId(45); mv.setMoleSymbol("Rh");mv.setMoleName("Rhodium"); mv.setWeight(new Double(102.9055)); hm.put("Rh",mv);
      mv=new Element();
      mv.setPeriodicId(46); mv.setMoleSymbol("Pd");mv.setMoleName("Palladium"); mv.setWeight(new Double(106.42)); hm.put("Pd",mv);
      mv=new Element();
      mv.setPeriodicId(47); mv.setMoleSymbol("Ag");mv.setMoleName("Silver"); mv.setWeight(new Double(107.8682)); hm.put("Ag",mv);
      mv=new Element();
      mv.setPeriodicId(48); mv.setMoleSymbol("Cd");mv.setMoleName("Cadmium"); mv.setWeight(new Double(112.411));  hm.put("Cd",mv);
      mv=new Element();
      mv.setPeriodicId(49); mv.setMoleSymbol("In");mv.setMoleName("Indium"); mv.setWeight( new Double(114.818)); hm.put("In",mv);
      mv=new Element();
      mv.setPeriodicId(50); mv.setMoleSymbol("Sn");mv.setMoleName("Tin"); mv.setWeight( new Double(118.71)); hm.put("Sn",mv);
      mv=new Element();
      mv.setPeriodicId(51); mv.setMoleSymbol("Sb");mv.setMoleName("Antimony"); mv.setWeight( new Double(121.76)); hm.put("Sb",mv);
      mv=new Element();
      mv.setPeriodicId(52); mv.setMoleSymbol("I");mv.setMoleName("Tellurium");  mv.setWeight(new Double(126.9045)); hm.put("I",mv);
      mv=new Element();
      mv.setPeriodicId(53); mv.setMoleSymbol("Te");mv.setMoleName("Iodine"); mv.setWeight(new Double(127.6)); hm.put("Te",mv);
      mv=new Element();
      mv.setPeriodicId(54); mv.setMoleSymbol("Xe");mv.setMoleName("Xenon"); mv.setWeight(new Double(131.293)); hm.put("Xe",mv);
      mv=new Element();
      mv.setPeriodicId(55); mv.setMoleSymbol("Cs");mv.setMoleName("Caesium (Cesium)"); mv.setWeight( new Double(132.9055)); hm.put("Cs",mv);
      mv=new Element();
      mv.setPeriodicId(56); mv.setMoleSymbol("Ba");mv.setMoleName("Barium"); mv.setWeight(new Double(137.327)); hm.put("Ba",mv);
      mv=new Element();
      mv.setPeriodicId(57); mv.setMoleSymbol("La");mv.setMoleName("Lanthanum"); mv.setWeight(new Double(138.9055)); hm.put("La",mv);
      mv=new Element();
      mv.setPeriodicId(58); mv.setMoleSymbol("Ce");mv.setMoleName("Cerium"); mv.setWeight(new Double(140.116)); hm.put("Ce",mv);
      mv=new Element();
      mv.setPeriodicId(59); mv.setMoleSymbol("Pr");mv.setMoleName("Praseodymium"); mv.setWeight( new Double(140.9077)); hm.put("Pr",mv);
      mv=new Element();
      mv.setPeriodicId(60); mv.setMoleSymbol("Nd");mv.setMoleName("Neodymium"); mv.setWeight(new Double(144.24)); hm.put("Nd",mv);
      mv=new Element();
      mv.setPeriodicId(61); mv.setMoleSymbol("Pm");mv.setMoleName("Promethium"); mv.setWeight(new Double(145));  hm.put("Pm",mv);
      mv=new Element();
      mv.setPeriodicId(62); mv.setMoleSymbol("Sm");mv.setMoleName("Samarium"); mv.setWeight( new Double(150.36)); hm.put("Sm",mv);
      mv=new Element();
      mv.setPeriodicId(63); mv.setMoleSymbol("Eu");mv.setMoleName("Europium"); mv.setWeight(new Double(151.964)); hm.put("Eu",mv);
      mv=new Element();
      mv.setPeriodicId(64); mv.setMoleSymbol("Gd");mv.setMoleName("Gadolinium"); mv.setWeight( new Double(157.25));  hm.put("Gd",mv);
      mv=new Element();
      mv.setPeriodicId(65); mv.setMoleSymbol("Tb");mv.setMoleName("Terbium"); mv.setWeight(new Double(158.9253)); hm.put("Tb",mv);
      mv=new Element();
      mv.setPeriodicId(66); mv.setMoleSymbol("Dy");mv.setMoleName("Dysprosium"); mv.setWeight(new Double(162.5)); hm.put("Dy",mv);
      mv=new Element();
      mv.setPeriodicId(67);mv.setMoleSymbol("Ho");mv.setMoleName("Holmium"); mv.setWeight(new Double(164.9303)); hm.put("Ho",mv);
      mv=new Element();
      mv.setPeriodicId(68); mv.setMoleSymbol("Er");mv.setMoleName("Erbium"); mv.setWeight(new Double(167.259)); hm.put("Er",mv);
      mv=new Element();
      mv.setPeriodicId(69); mv.setMoleSymbol("Tm");mv.setMoleName("Thulium"); mv.setWeight(new Double(168.9342)); hm.put("Tm",mv);
      mv=new Element();
      mv.setPeriodicId(70); mv.setMoleSymbol("Yb");mv.setMoleName("Ytterbium"); mv.setWeight( new Double(173.04)); hm.put("Yb",mv);
      mv=new Element();
      mv.setPeriodicId(71); mv.setMoleSymbol("Lu");mv.setMoleName("Lutetium"); mv.setWeight(new Double(174.967)); hm.put("Lu",mv);
      mv=new Element();
      mv.setPeriodicId(72); mv.setMoleSymbol("Hf");mv.setMoleName("Hafnium"); mv.setWeight(new Double(178.49)); hm.put("Hf",mv);
      mv=new Element();
      mv.setPeriodicId(73); mv.setMoleSymbol("Ta");mv.setMoleName("Tantalum"); mv.setWeight( new Double(180.9479)); hm.put("Ta",mv);
      mv=new Element();
      mv.setPeriodicId(74); mv.setMoleSymbol("W");mv.setMoleName("Tungsten"); mv.setWeight(new Double(183.84)); hm.put("W",mv);
      mv=new Element();
      mv.setPeriodicId(75); mv.setMoleSymbol("Re");mv.setMoleName("Rhenium"); mv.setWeight( new Double(186.207)); hm.put("Re",mv);
      mv=new Element();
      mv.setPeriodicId(76); mv.setMoleSymbol("Os");mv.setMoleName("Osmium"); mv.setWeight(new Double(190.23)); hm.put("Os",mv);
      mv=new Element();
      mv.setPeriodicId(77); mv.setMoleSymbol("Ir");mv.setMoleName("Iridium"); mv.setWeight(new Double(192.217)); hm.put("Ir",mv);
      mv=new Element();
      mv.setPeriodicId(78);mv.setMoleSymbol("Pt");mv.setMoleName("Platinum"); mv.setWeight(new Double(195.078)); hm.put("Pt",mv);
      mv=new Element();
      mv.setPeriodicId(79); mv.setMoleSymbol("Au");mv.setMoleName("Gold"); mv.setWeight( new Double(196.9665)); hm.put("Au",mv);
      mv=new Element();
      mv.setPeriodicId(80); mv.setMoleSymbol("Hg");mv.setMoleName("Mercury"); mv.setWeight( new Double(200.59)); hm.put("Hg",mv);
      mv=new Element();
      mv.setPeriodicId(81); mv.setMoleSymbol("Tl");mv.setMoleName("Thallium"); mv.setWeight( new Double(204.3833));  hm.put("Tl",mv);
      mv=new Element();
      mv.setPeriodicId(82); mv.setMoleSymbol("Pb");mv.setMoleName("Lead"); mv.setWeight(new Double(207.2)); hm.put("Pb",mv);
      mv=new Element();
      mv.setPeriodicId(83); mv.setMoleSymbol("Bi");mv.setMoleName("Bismuth"); mv.setWeight(new Double(208.9804));  hm.put("Bi",mv);
      mv=new Element();
      mv.setPeriodicId(84); mv.setMoleSymbol("Po");mv.setMoleName("Polonium"); mv.setWeight(new Double(209)); hm.put("Po",mv);
      mv=new Element();
      mv.setPeriodicId(85); mv.setMoleSymbol("At");mv.setMoleName("Astatine"); mv.setWeight(new Double(210)); hm.put("At",mv);
      mv=new Element();
      mv.setPeriodicId(86); mv.setMoleSymbol("Rn");mv.setMoleName("Radon"); mv.setWeight(new Double(222)); hm.put("Rn",mv);
      mv=new Element();
      mv.setPeriodicId(87); mv.setMoleSymbol("Fr");mv.setMoleName("Francium"); mv.setWeight( new Double(223)); hm.put("Fr",mv);
      mv=new Element();
      mv.setPeriodicId(88); mv.setMoleSymbol("Ra");mv.setMoleName("Radium"); mv.setWeight(new Double(226));  hm.put("Ra",mv);
      mv=new Element();
      mv.setPeriodicId(89); mv.setMoleSymbol("Ac");mv.setMoleName("Actinium"); mv.setWeight(new Double(227));  hm.put("Ac",mv);
      mv=new Element();
      mv.setPeriodicId(90); mv.setMoleSymbol("Pa");mv.setMoleName("Thorium"); mv.setWeight( new Double(231.0359)); hm.put("Pa",mv);
      mv=new Element();
      mv.setPeriodicId(91); mv.setMoleSymbol("Th");mv.setMoleName("Protactinium"); mv.setWeight(new Double(232.0381));  hm.put("Th",mv);
      mv=new Element();
      mv.setPeriodicId(92); mv.setMoleSymbol("U"); mv.setMoleName("Uranium"); mv.setWeight(new Double(238.0289)); hm.put("U",mv);
      mv=new Element();
      mv.setPeriodicId(93); mv.setMoleSymbol("Np");mv.setMoleName("Neptunium"); mv.setWeight(new Double(237));  hm.put("Np",mv);
      mv=new Element();
      mv.setPeriodicId(94); mv.setMoleSymbol("Pu");mv.setMoleName("Plutonium");  mv.setWeight(new Double(244)); hm.put("Pu",mv);
      mv=new Element();
      mv.setPeriodicId(94); mv.setMoleSymbol("Am");mv.setMoleName("Americium");  mv.setWeight(new Double(243)); hm.put("Am",mv);
      mv=new Element();
      mv.setPeriodicId(96); mv.setMoleSymbol("Cm");mv.setMoleName("Curium");  mv.setWeight(new Double(247)); hm.put("Cm",mv);
      mv=new Element();
      mv.setPeriodicId(97); mv.setMoleSymbol("Bk");mv.setMoleName("Berkelium");  mv.setWeight(new Double(247)); hm.put("Bk",mv);
      mv=new Element();
      mv.setPeriodicId(98); mv.setMoleSymbol("Cf"); mv.setMoleName("Californium"); mv.setWeight( new Double(251)); hm.put("Cf",mv);
      mv=new Element();
      mv.setPeriodicId(99); mv.setMoleSymbol("Es"); mv.setMoleName("Einsteinium"); mv.setWeight( new Double(252)); hm.put("Es",mv);
      mv=new Element();
      mv.setPeriodicId(100); mv.setMoleSymbol("Fm");mv.setMoleName("Fermium"); mv.setWeight( new Double(257)); hm.put("Em",mv);
      mv=new Element();
      mv.setPeriodicId(101); mv.setMoleSymbol("Md");mv.setMoleName("Mendelevium"); mv.setWeight( new Double(258)); hm.put("Md",mv);
      mv=new Element();
      mv.setPeriodicId(102); mv.setMoleSymbol("No");mv.setMoleName("Nobelium"); mv.setWeight( new Double(259)); hm.put("No",mv);
      mv=new Element();
      mv.setPeriodicId(103); mv.setMoleSymbol("Rf"); mv.setMoleName("Lawrencium");mv.setWeight( new Double(261)); hm.put("Rf",mv);
      mv=new Element();
      mv.setPeriodicId(104); mv.setMoleSymbol("Lr"); mv.setMoleName("Rutherfordium");mv.setWeight( new Double(262)); hm.put("Lr",mv);
      mv=new Element();
      mv.setPeriodicId(105); mv.setMoleSymbol("Db");mv.setMoleName("Dubnium"); mv.setWeight( new Double(262)); hm.put("Db",mv);
      mv=new Element();
      mv.setPeriodicId(106); mv.setMoleSymbol("Sg");mv.setMoleName("Seaborgium"); mv.setWeight( new Double(266)); hm.put("Sg",mv);
      mv=new Element();
      mv.setPeriodicId(107); mv.setMoleSymbol("Bh"); mv.setMoleName("Bohrium");mv.setWeight( new Double(264)); hm.put("Bh",mv);
      mv=new Element();
      mv.setPeriodicId(108); mv.setMoleSymbol("Hs");mv.setMoleName("Hassium"); mv.setWeight( new Double(277)); hm.put("Hs",mv);
      mv=new Element();
      mv.setPeriodicId(109); mv.setMoleSymbol("Mt");mv.setMoleName("Meitnerium"); mv.setWeight( new Double(268)); hm.put("Mt",mv);
      mv=new Element();
      mv.setPeriodicId(110); mv.setMoleSymbol("Ds");mv.setMoleName("Darmstadtium"); mv.setWeight( new Double(280)); hm.put("Ds",mv);
      mv=new Element();
      mv.setPeriodicId(111); mv.setMoleSymbol("Rg");mv.setMoleName("Roentgenium"); mv.setWeight( new Double(272)); hm.put("Rg",mv);
      mv=new Element();
      mv.setPeriodicId(112); mv.setMoleSymbol("Cp");mv.setMoleName("Copernicium"); mv.setWeight( new Double(277)); hm.put("Cp",mv);
      mv=new Element();
      mv.setPeriodicId(113); mv.setMoleSymbol("Uut");mv.setMoleName("Ununtrium"); mv.setWeight( new Double(280)); hm.put("Uut",mv);
      mv=new Element();
      mv.setPeriodicId(114); mv.setMoleSymbol("Uuq");mv.setMoleName("Ununquadium"); mv.setWeight( new Double(280)); hm.put("Uuq",mv);
      mv=new Element();
      mv.setPeriodicId(115); mv.setMoleSymbol("Uup");mv.setMoleName("Ununpentium"); mv.setWeight( new Double(280)); hm.put("Uup",mv);
      mv=new Element();
      mv.setPeriodicId(116); mv.setMoleSymbol("Uuh");mv.setMoleName("Ununhexium"); mv.setWeight( new Double(280)); hm.put("Uuh",mv);
      mv=new Element();
      mv.setPeriodicId(117); mv.setMoleSymbol("Uus");mv.setMoleName("Ununseptium"); mv.setWeight( new Double(280)); hm.put("Uus",mv);
      mv=new Element();
      mv.setPeriodicId(118); mv.setMoleSymbol("Uuo");mv.setMoleName("Ununoctium"); mv.setWeight( new Double(280)); hm.put("Uuo",mv);
      
      
      mv=new Element();
      mv.setPeriodicId(130); mv.setMoleSymbol("SO4");mv.setMoleName("sulphate"); mv.setWeight( new Double(96.07)); 
      mv.setDefaultValancy("-2");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "-2";
      mv.setValency(valancy);hm.put("SO4",mv);
      mv=new Element();
      mv.setPeriodicId(131); mv.setMoleSymbol("OH");mv.setMoleName("Hydroxide"); mv.setWeight(new Double(17.008)); 
      mv.setDefaultValancy("-1");
      valancy =null;
      valancy =  new String[1];
      valancy[0] = "-1";
      mv.setValency(valancy);hm.put("OH",mv);
     }
	/**
	 * @return the hm
	 */
	public static Hashtable<String, Element> getHm() {
		return hm;
	}
	/**
	 * @param hm the hm to set
	 */
	public static void setHm(Hashtable<String, Element> hm) {
		PeriodicTable.hm = hm;
	}
	
	/*private static PeriodicTable getInstance() {
		if (tbl == null) {
			tbl = new PeriodicTable();
		}
		return tbl;
	}*/

}

